version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8002:8002"
    env_file:
      - .env
    environment:
      # Database connection for internal Docker network
      DATABASE_URL: postgresql://postgres:admin@db:5432/AI_CHATBOT
      # Optional: You can override OpenAI API key here or keep it in .env
      # OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/app # Mount local code for hot reload during development
      - /app/__pycache__ # Exclude pycache from volume
    restart: unless-stopped
    networks:
      - app_network

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: AI_CHATBOT
      POSTGRES_HOST_AUTH_METHOD: trust # For development only
    ports:
      - "5444:5432" # Map host:5444 to container:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Optional: initialization script
    networks:
      - app_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d AI_CHATBOT"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres_data:
    driver: local

networks:
  app_network:
    driver: bridge
