services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "80:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:admin123@database-1.ccda62qsu988.us-east-1.rds.amazonaws.com:5432/postgres
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
      PORT: 8000
    volumes:
      - ./:/app
      - /app/__pycache__
    restart: unless-stopped
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "python /app/healthcheck.py"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 60s

networks:
  app_network:
    driver: bridge
